os:
  - linux
  - osx

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - WORKING_DIR=~/code/git/dotfiles
before_install:
  - mkdir -p $WORKING_DIR
  - cp -r . $WORKING_DIR

install:
  - pip install ansible

script:
  - $WORKING_DIR/bootstrap.sh
