---
- hosts: all

  vars_files:
   - ansible/vars/default_config.yaml

  tasks:
    - include_tasks: ansible/tasks/basic_setup.yaml
    - include_tasks: ansible/tasks/debian_setup.yaml
    # - include_tasks: ansible/tasks/installs_mac.yaml
    - include_tasks: ansible/tasks/installs_pipx.yaml
    # - include_tasks: ansible/tasks/installs_snap.yaml
    - include_tasks: ansible/tasks/installs_vim_plugins.yaml
    # - include_tasks: ansible/tasks/conda_env.yaml
