---
- hosts: all

  vars_files:
   - ansible/vars/default_config.yaml

  tasks:
    - name: basic setup
      ansible.builtin.include_tasks: ansible/tasks/basic_setup.yaml
    - name: debian setup
      ansible.builtin.include_tasks: ansible/tasks/debian_setup.yaml
      when: ansible_os_family | lower == 'debian'
    - name: snap installs
      ansible.builtin.include_tasks: ansible/tasks/installs_snap.yaml
      when: ansible_os_family | lower == 'debian'
    # - name: mac installs
    #   ansible.builtin.include_tasks: ansible/tasks/installs_mac.yaml
    #   when: ansible_os_family | lower == 'darwin'
    # - name: pipx installs
    #   ansible.builtin.include_tasks: ansible/tasks/installs_pipx.yaml
    # - name: vim plugin installs
    #   ansible.builtin.include_tasks: ansible/tasks/installs_vim_plugins.yaml
    # - name: clone git repos
    #   ansible.builtin.include_tasks: ansible/tasks/git_repos.yaml
    # - name: conda setup
    #   ansible.builtin.include_tasks: ansible/tasks/conda_env.yaml
