- name: Setup dev environment
  hosts: local

  tasks:

    - name: Create dirs
      ansible.builtin.apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - bat
        - chromium
        - curl
        - exfat-fuse
        - exfat-utils
        - gnome-shell-pomodoro
        - gnome-tweaks
        - jq
        - git
        - neofetch
        - pipx
        - ripgrep
        - snapd
        - tldr
        - tree
        - vim
        - wget
        - xclip
        - zsh

  tasks:
    - name: Create symlink for bat
      ignore_errors: yes
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: ~/.local/bin/bat
        state: link

    - name: Install snaps
      community.general.snap:
        name:
          - code --classic
          - docker
          - libreoffice
          - pycharm-community --classic
          - intellij-idea-community --classic
          - vlc
