- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"
  ignore_errors: true

- name: Create symlink for bat
  ignore_errors: true
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: ~/.local/bin/bat
    state: link

- name: Enable firewall
  ansible.builtin.shell: sudo ufw enable

- name: Setup gnome terminal settings
  ansible.builtin.shell:
    - gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ next-tab '<Primary>Tab'
    - gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ prev-tab '<Primary><Shift>Tab'

# - name: Change default bluetooth settings
#   become: true
#   ansible.builtin.lineinfile:
#     dest: /etc/bluetooth/main.conf
#     line: 'ControllerMode = bredr'
#     insertafter: '^#ControllerMode = dual'
#     state: present
# when: ansible_os_family | lower == 'debian'
