- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"
  ignore_errors: true

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_packages }}"

- name: Create custom symlinks for bat and fd
  ignore_errors: true
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: /usr/bin/batcat, dest: ~/.local/bin/bat }
    - { src: /usr/bin/fdfind, dest: ~/.local/bin/fd }

- name: Enable firewall
  ansible.builtin.shell: sudo ufw enable

- name: Setup gnome terminal settings
  ansible.builtin.shell:
    "gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ {{ item }}"
  loop:
    - next-tab '<Primary>Tab'
    - prev-tab '<Primary><Shift>Tab'
  when: ansible_distribution | lower == 'pop!_os'

# - name: Setup dns addresses
#   ansible.builtin.shell:
#     "nmcli connection modify {{ item.connection_name }} {{ item.type }} '{{ item.addresses }}'"
#   loop:
#     - { connection_name: "{{ ansible_default_ipv4['interface'] }}", type: ipv4.dns, addresses: "{{ dns_addresses['ipv4'] | join(',') }}" }
#     - { connection_name: "{{ ansible_default_ipv6['interface'] }}", type: ipv6.dns, addresses: "{{ dns_addresses['ipv6'] | join(',') }}" }
#   when: ansible_distribution | lower == 'pop!_os'

# - name: Change default bluetooth settings
#   become: true
#   ansible.builtin.lineinfile:
#     dest: /etc/bluetooth/main.conf
#     line: 'ControllerMode = bredr'
#     insertafter: '^#ControllerMode = dual'
#     state: present
# when: ansible_os_family | lower == 'debian'
