- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"
  ignore_errors: true
  tags:
    - linux
    - apt

- name: Install flatpak packages
  ignore_errors: true
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_packages }}"
  tags:
    - linux
    - flatpak

# - name: Flatpak customization
  # ansible.builtin.command: flatpak override --user --filesystem=/run/docker.sock com.visualstudio.code

- name: Create custom symlinks for bat and fd
  ignore_errors: true
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: /usr/bin/batcat, dest: ~/.local/bin/bat }
    - { src: /usr/bin/fdfind, dest: ~/.local/bin/fd }
  tags:
    - linux

- name: Enable firewall
  ansible.builtin.shell: sudo ufw enable
  tags:
    - linux

- name: Setup gnome terminal settings
  ansible.builtin.shell:
    "gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ {{ item }}"
  loop:
    - next-tab '<Primary>Tab'
    - prev-tab '<Primary><Shift>Tab'
  when: ansible_distribution | lower == 'pop!_os'
  tags:
    - linux

- name: download neovim latest
  ansible.builtin.get_url:
    # url: https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.tar.gz
    url: "https://github.com/neovim/neovim/releases/download/v{{ neovim['version'] }}/nvim-linux64.tar.gz"
    dest: /tmp
    checksum: "sha256: {{ neovim['sha256'] }}"
  tags:
    - linux

- name: download nerd fonts
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf"
    dest: ~/.local/share/fonts/Droid Sans Mono for Powerline Nerd Font Complete.otf
  tags:
    - linux
    
# After installing your font, you will have to refresh your font cache by doing fc-cache -f -v. Then you will have to change your terminal settings to use the font you just installed. Please refer to your terminal's documentation for changing the terminal font.

# - name: Setup dns addresses
#   ansible.builtin.shell:
#     "nmcli connection modify {{ item.connection_name }} {{ item.type }} '{{ item.addresses }}'"
#   loop:
#     - { connection_name: "{{ ansible_default_ipv4['interface'] }}", type: ipv4.dns, addresses: "{{ dns_addresses['ipv4'] | join(',') }}" }
#     - { connection_name: "{{ ansible_default_ipv6['interface'] }}", type: ipv6.dns, addresses: "{{ dns_addresses['ipv6'] | join(',') }}" }
#   when: ansible_distribution | lower == 'pop!_os'

# - name: Change default bluetooth settings
#   become: true
#   ansible.builtin.lineinfile:
#     dest: /etc/bluetooth/main.conf
#     line: 'ControllerMode = bredr'
#     insertafter: '^#ControllerMode = dual'
#     state: present
# when: ansible_os_family | lower == 'debian'
