- name: "print variables"
  debug:
    msg: 
      - "dotfiles_dir is {{ dotfiles_dir }}"

- name: Create dirs
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
  loop: "{{ base_directory_structure }}"

- name: Create symlinks in home ~
  ignore_errors: true
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    follow: no
    force: false
  loop: "{{ dotfiles }}"

- name: Create symlinks in ~/.config
  ignore_errors: true
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "~/.config/{{ item }}"
    state: link
    follow: no
    force: true
  loop: "{{ dotfiles }}"

