- name: Create dirs
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
  loop: "{{ base_directory_structure }}"

- name: Create symlinks in home ~
  ignore_errors: true
  ansible.builtin.file:
    src: '{{ dotfiles_dir }}/{{ item }}'
    dest: "~/{{ item }}"
    state: link
    force: true
  loop: "{{ dotfiles }}"

- name: Create symlinks in ~/.config
  ignore_errors: true
  ansible.builtin.file:
    src: '{{ dotfiles_dir }}/{{ item }}'
    dest: "~/.config/{{ item }}"
    state: link
  loop: "{{ dotfiles }}"

