- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"
  when: ansible_os_family | lower == 'debian'
  ignore_errors: true

# - name: Change default bluetooth settings
  # become: true
  # ansible.builtin.lineinfile:
  #   dest: /etc/bluetooth/main.conf
  #   line: 'ControllerMode = bredr'
  #   insertafter: '^#ControllerMode = dual'
  #   state: present
  # when: ansible_os_family | lower == 'debian'

- name: Create symlink for bat
  ignore_errors: true
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: ~/.local/bin/bat
    state: link
  when: ansible_os_family | lower == 'debian'

- name: Enable firewall
  ansible.builtin.shell: sudo ufw enable
  when: ansible_os_family | lower == 'debian'

- name: Setup gnome terminal settings
  ansible.builtin.shell: cat ~/.gnome-terminal.conf | dconf load /org/gnome/terminal/legacy/profiles:/
  when: ansible_os_family | lower == 'debian'
