- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"
  when: ansible_os_family | lower == 'debian'

- name: Change default bluetooth settings
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/bluetooth/main.conf
    line: 'ControllerMode = bredr'
    insertafter: '^#ControllerMode = dual'
    state: present
  when: ansible_os_family | lower == 'debian'

- name: Create symlink for bat
  ignore_errors: yes
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: ~/.local/bin/bat
    state: link
  when: ansible_os_family | lower == 'debian'
