- name: Pipx install
  command:
    cmd: "pipx install {{ item }}"
  tags:
  - pipx
  loop:
    - awscli
    - black
    - bpytop
    - httpx[cli]
    - 'maestral[gui]'
    - parquet-tools
    - tldr
    
