- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: installed
    update_homebrew: yes
  tags:
    - brew
  when: ansible_os_family | lower == 'darwin'
  loop: "{{ homebrew_packages }}"

- name: Install homebrew cask packages
  community.general.homebrew_cask:
    name: '{{ item }}'
    state: installed
  tags:
  - brew
  when: ansible_os_family | lower == 'darwin'
  loop: "{{ homebrew_cask_packages }}"

- name: modify macOS user defaults
  community.general.osx_defaults:
    domain: com.microsoft.VSCode
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present
  when: ansible_os_family | lower == 'darwin'
