- name: Install vim plugins
  ansible.builtin.git:
    repo: "{{ item.plugin_git_source }}"
    dest: "{{ item.plugin_target_path }}"
  loop: "{{ vim_plugins }}"

# git clone https://github.com/preservim/nerdtree.git ~/.vim/pack/vendor/start/nerdtree
# vim -u NONE -c "helptags ~/.vim/pack/vendor/start/nerdtree/doc" -c q

