- name: Setup dev environment
  hosts: local

  tasks:

    - name: Install apt packages
      become: true
      #become_user: root
      #become_method: sudo
      ansible.builtin.apt:
        update_cache: yes
        name: "{{ item }}"
        #pkg: 
        #  - "{{ item }}"
        state: present
      loop:
        - bat
        - curl
        - exfat-fuse
        - exfat-utils
        - jq
        - git
        - neofetch
        - pipx
        - ripgrep
        - snapd
        - tldr
        - tree
        - vim
        - wget
        - xclip
        - zsh

    - name: Create symlink for bat
      ignore_errors: yes
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: ~/.local/bin/bat
        state: link

