- name: Setup dev environment
  hosts: local

  tasks:
    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: installed
        update_homebrew: yes
      tags:
      - brew
      loop:
        - bat
        - jq
        - pipx
        - starship
        - tree

    - name: Install homebrew cask packages
      community.general.homebrew_cask:
        name: '{{ item }}'
        state: installed
      tags:
      - brew
      loop:
        - dbeaver-community
        - docker
        - firefox
        - intellij-idea
        - iterm2
        - joplin
        - maccy
        - postman
        - pycharm
        - rectangle
        #- visual-studio-code
