- name: Setup dev environment
  hosts: local

  tasks:

    - name: Install snaps
      community.general.snap:
        name:
          - code --classic
          - docker
          - libreoffice
          - pycharm-community --classic
          #- intellij-idea-community --classic
          #- vlc

