- name: apply common configuration
  hosts: all
  vars_files:
   - vars/default_config.yaml
  roles:
    - base
    - misc

- name: linux setup
  hosts: all
  vars_files:
   - vars/default_config.yaml
  roles:
    - role: linux
      when: ansible_os_family | lower == 'debian'

# - name: mac setup
#   hosts: all
#   vars_files:
#    - vars/default_config.yaml
#   roles:
#     - role: mac
#       when: ansible_os_family | lower == 'darwin'
