name: main
env:
  WORKING_DIR: ~/code/git/dotfiles
on: [push]
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: |
          pwd
          mkdir -p $WORKING_DIR
          pwd
          cp -r . $WORKING_DIR
          pwd
          pip install --upgrade pip ansible pipx
          source $WORKING_DIR/bootstrap.sh
