name: main
env:
  WORKING_DIR: $HOME/code/git/dotfiles
on: [push]
jobs:
  setup-environment:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Ubuntu packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y just=1.22.0
      - name: Install package on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install just
      - run: |
          just setup
